CREATE TABLE IF NOT EXISTS notes (
    note_id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT,
    tags TEXT NOT NULL DEFAULT '[]',
    is_favorite BOOLEAN NOT NULL DEFAULT false,
    is_work_log BOOLEAN NOT NULL DEFAULT false,
    is_trash BOOLEAN NOT NULL DEFAULT false,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
